name = "movie-master-visitor-counter"
main = "src/index.js"
compatibility_date = "2026-08-31"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "movie-master-visitors"
database_id = "a00af085-9023-4092-8090-d2a5778a9b42"
